<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\TestProject.props" />

  <PropertyGroup>
    <RootNamespace>ProjectX.Application.UnitTests</RootNamespace>
    <AssemblyName>ProjectX.Application.UnitTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
  </ItemGroup>
</Project>
